on:
  pull_request_review:
    types: [submitted]

name: Build My Apps

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    name: Build and Release new apk pull request
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}